version: "3"

services:
  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      dockerfile: ./deploy/Dockerfile
      context: .
    restart: always
    ports:
      - "8000:8000"
    networks:
      - music-room

  db:
    image: "postgres:16.0"
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - music-room

volumes:
  postgres:

networks:
  music-room:
    external: true