[tool.poetry]
name = "innohassle-musicroom"
version = "0.1.0"
description = ""
authors = ["Saveliy <s.lekhtin@innopolis.university>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.103.1"
uvicorn = "^0.23.2"
sqlalchemy = "^2.0.20"
python-dotenv = "^1.0.0"
black = "^23.9.1"
isort = "^5.12.0"
asyncpg = "^0.28.0"
pydantic-settings = "^2.0.3"
greenlet = "^2.0.2"
cryptography = "^41.0.4"
pillow = "^10.0.1"

[tool.black]
line-length = 120 # Maximum line length


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
