$schema: https://json-schema.org/draft-07/schema
$defs:
  ApiSettings:
    properties:
      app_root_path:
        default: ''
        description: Prefix for the API path (e.g. "/api/v0")
        title: App Root Path
        type: string
      db_url:
        default: postgresql+asyncpg://postgres:postgres@localhost:5432/postgres
        example: postgresql+asyncpg://user:password@localhost:5432/db_name
        title: Db Url
        type: string
      bot_token:
        description: Bot token from @BotFather
        example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        title: Bot Token
        type: string
      jwt_private_key:
        description: Private key for JWT. Use 'openssl genrsa -out private.pem 2048'
          to generate keys
        format: password
        title: Jwt Private Key
        type: string
        writeOnly: true
      jwt_public_key:
        description: Public key for JWT. Use 'openssl rsa -in private.pem -pubout
          -out public.pem' to generate keys
        title: Jwt Public Key
        type: string
      smtp_server:
        example: smtp.gmail.com
        title: Smtp Server
        type: string
      smtp_port:
        default: 587
        title: Smtp Port
        type: integer
      smtp_username:
        example: some-username@gmail.com
        title: Smtp Username
        type: string
      smtp_password:
        example: xxxxxxxx
        title: Smtp Password
        type: string
      crypto_password:
        description: Run 'openssl rand -hex 32' to generate key
        example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        format: binary
        title: Crypto Password
        type: string
      crypto_salt:
        example: xxxxxxxxxxxxxxxx
        format: binary
        title: Crypto Salt
        type: string
      api_key:
        description: API key for the Music Room API
        example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        title: Api Key
        type: string
    required:
    - bot_token
    - jwt_private_key
    - jwt_public_key
    - smtp_server
    - smtp_username
    - smtp_password
    - crypto_password
    - crypto_salt
    - api_key
    title: ApiSettings
    type: object
  BotSettings:
    properties:
      environment:
        allOf:
        - $ref: '#/$defs/Environment'
        default: development
      bot_token:
        description: Bot token from @BotFather
        format: password
        title: Bot Token
        type: string
        writeOnly: true
      api_url:
        title: Api Url
        type: string
      redis_url:
        anyOf:
        - format: password
          type: string
          writeOnly: true
        - type: 'null'
        default: null
        title: Redis Url
    required:
    - bot_token
    - api_url
    title: BotSettings
    type: object
  Environment:
    enum:
    - development
    - production
    - staging
    title: Environment
    type: string
properties:
  api_settings:
    anyOf:
    - $ref: '#/$defs/ApiSettings'
    - type: 'null'
    default: null
  bot_settings:
    anyOf:
    - $ref: '#/$defs/BotSettings'
    - type: 'null'
    default: null
title: Settings
type: object
