$schema: "./settings.schema.yaml"
# ---------- Application settings ----- #
SMTP_SERVER: ...
SMTP_USERNAME: ...
SMTP_PASSWORD: ...
# Run 'openssl rand -hex 32' to generate password
CRYPTO_PASSWORD: ...
# Run 'openssl rand -hex 16' to generate salt
CRYPTO_SALT: ...
DB_URL: "postgresql+asyncpg://postgres:postgres@localhost:5432/postgres"
